export const storage = [
  {
    product: "SET SECCIONAL CERVIA 3 PIEZAS ALUMINIO - NEGRO",
    id: 1,
    price: 1699990,
    image: "./assets/sofas/sofa-1.jpeg",
    category: "sofa", 
    quantity: 1,
  },
  {
    product: "SOFÁ SECCIONAL CARTER DERECHO TELA - DENIM",
    id: 2,
    price: 1199990,
    image: "./assets/sofas/sofa-2.jpeg",
    category: "sofa", 
    quantity: 1,
  },
  {
    product: "SOFÁ SECCIONAL COPELAND DERECHO CUERO - ICE",
    id: 3,
    price: 1599990,
    image: "./assets/sofas/sofa-3.jpeg",
    category: "sofa", 
    quantity: 1,
  },
  {
    product: "SOFÁ SECCIONAL HARBORD DERECHO TELA - BEIGE",
    id: 4,
    price: 1099990,
    image: "./assets/sofas/sofa-4.jpeg",
    category: "sofa", 
    quantity: 1,
  },
  {
    product: "SOFÁ SECCIONAL DUNSTER IZQUIERDO TELA - BEIGE",
    id: 5,
    price: 1699990,
    image: "./assets/sofas/sofa-5.jpeg",
    category: "sofa", 
    quantity: 1,
  },
  {
    product: "SOFÁ SECCIONAL SHANKLIN TELA 3 PIEZAS - DENIM",
    id: 6,
    price: 1799990,
    image: "./assets/sofas/sofa-6.jpeg",
    category: "sofa", 
    quantity: 1,
  },
  {
    product: "SOFÁ SECCIONAL LONDON IZQUIERDO CUERO - TAUPE",
    id: 7,
    price: 2199990,
    image: "./assets/sofas/sofa-7.jpeg",
    category: "sofa", 
    quantity: 1,
  },
  {
    product: "SOFÁ SECCIONAL WESTWOOD DERECHO CUERO",
    id: 8,
    price: 2699990,
    image: "./assets/sofas/sofa-8.jpeg",
    category: "sofa", 
    quantity: 1,
  },
  {
    product: "VELADOR TIVOLI",
    id: 9,
    price: 339990,
    image: "assets/Veladores/velador-1.jpeg",
    category: "velador", 
    quantity: 1,
  },
  {
    product: "VELADOR BRERA (52 CM ANCHO)",
    id: 10,
    price: 214990,
    image: "assets/Veladores/velador-2.jpeg",
    category: "velador", 
    quantity: 1,
  },
  {
    product: "VELADOR ELGIN",
    id: 11,
    price: 219990,
    image: "assets/Veladores/velador-3.jpeg",
    category: "velador", 
    quantity: 1,
  },
  {
    product: "VELADOR FERRARA",
    id: 12,
    price: 64990,
    image: "assets/Veladores/velador-4.jpeg",
    category: "velador", 
    quantity: 1,
  },
  {
    product: "VELADOR DOLCE",
    id: 13,
    price: 129990,
    image: "assets/Veladores/velador-5.jpeg",
    category: "velador", 
    quantity: 1,
  },
  {
    product: "VELADOR FOLGATE",
    id: 14,
    price: 299990,
    image: "assets/Veladores/velador-6.jpeg",
    category: "velador", 
    quantity: 1,
  },
  {
    product: "VELADOR SICILIA",
    id: 15,
    price: 109990,
    image: "assets/Veladores/velador-7.jpeg",
    category: "velador", 
    quantity: 1,
  },
  {
    product: "VELADOR LANCASTER",
    id: 16,
    price: 219990,
    image: "assets/Veladores/velador-8.jpeg",
    category: "velador", 
    quantity: 1,
  },
];



